name: taiko_songs
description: taiko song list.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  collection: ^1.17.2
  crypto: ^3.0.3
  device_info_plus: ^9.1.0
  dio: ^5.3.2
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  html: ^0.15.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  shared_preferences_field_delegate: ^1.0.0
  url_launcher: ^6.1.14
  widget_screenshot:
    git:
     url: https://github.com/AoEiuV020/widget_screenshot

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  rename: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/line/
    - assets/translate/


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/TaikoSongs.png"
  min_sdk_android: 19
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
